### PR TITLE
Update implementation_section_index.yml

### PR DESCRIPTION
**Pull request by YuryRog**

### CODE REVIEW

**Comment by Philip-Larsen-Donnelly** [comment]
Vittoria already asked me to add this document here: https://docs.dhis2.org/en/implement/health/immunization/expanded-programme-on-immunization-epi-aggregate/new-antigens-inclusion/malaria-vaccine.html

**Comment by olavpo** [comment]
@YuryRog and @Philip-Larsen-Donnelly - got confused, should this be closed or reviewed/approved?

**Comment by YuryRog** [comment]
@olavpo , this has now been resolved by @Philip-Larsen-Donnelly , thx
No further action needed

**Comment by Philip-Larsen-Donnelly** [comment]
@YuryRog I think we still want to merge this though, right?

**Comment by YuryRog** [comment]
Correct! @Philip-Larsen-Donnelly

**Comment by olavpo** [comment]
Change has already been applied

**Review by olavpo — APPROVED** [review]

**Pull request merged**
